//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Degage.Proxys {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Degage.Proxys.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当前运行时不支持创建动态代理类！ 的本地化字符串。
        /// </summary>
        internal static string E_CLRNotSupported {
            get {
                return ResourceManager.GetString("E_CLRNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理类型无效！只能为接口、抽象类、类。 的本地化字符串。
        /// </summary>
        internal static string E_ObjectFactoryProxyTypeInvaild {
            get {
                return ResourceManager.GetString("E_ObjectFactoryProxyTypeInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}：此代理成员已被忽略，且尚未实现 的本地化字符串。
        /// </summary>
        internal static string EF_IgnoredProxiedMemberWithAbstract {
            get {
                return ResourceManager.GetString("EF_IgnoredProxiedMemberWithAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被代理的方法未被正确处理：{0}。 的本地化字符串。
        /// </summary>
        internal static string EF_ProxiedMethodHandleErrorFormat {
            get {
                return ResourceManager.GetString("EF_ProxiedMethodHandleErrorFormat", resourceCulture);
            }
        }
    }
}
